name: Build

on: [push ,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: make init

      # - name: Run Linter
      #   run: make lint

      - name: Build Project
        run: make build

      # - name: Run Project
      #   run: make run

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/video_creator-*.tar.gz
